services:
  bot:
    container_name: bot_image
    build: ./bot
    environment:
      - TOKEN=${TOKEN}
      - RM_HOST=${RM_HOST}
      - RM_PORT=${RM_PORT}
      - RM_USER=${RM_USER}
      - RM_PASSWORD=${RM_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    env_file:
      - .env
  db:
    container_name: db_image
    build: 
      context: ./db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
      - DB_REPL_HOST=${DB_REPL_HOST}.my_network
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    env_file:
      - .env

  db_repl:
    container_name: db_repl_image
    build: 
      context: ./db_repl
    environment:
      - DB_HOST=${DB_HOST}.my_network
      - DB_PORT=${DB_PORT}
      - DB_REPL_HOST=${DB_REPL_HOST}
      - DB_REPL_PORT=${DB_REPL_PORT}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db

networks:
  default:
    name: my_network
